/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "DAC_1.h"
#include "S1_aliases.h"
#include "S1.h"
#include "I_aliases.h"
#include "I.h"
#include "DAC_2.h"
#include "Q_aliases.h"
#include "Q.h"
#include "S2_aliases.h"
#include "S2.h"
#include "Pin_Clk_aliases.h"
#include "Pin_Clk.h"
#include "ADC_1.h"
#include "Opamp_1.h"
#include "Opamp_2.h"
#include "ADC_2.h"
#include "Pin_Serial_aliases.h"
#include "Pin_Serial.h"
#include "ADC_1_IRQ.h"
#include "ADC_1_theACLK.h"
#include "ADC_1_Bypass_aliases.h"
#include "ADC_1_Bypass.h"
#include "ADC_2_IRQ.h"
#include "ADC_2_theACLK.h"
#include "ADC_2_Bypass_aliases.h"
#include "ADC_2_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

